import Head from "next/head";
import { Flex, Text, Link, Image, DarkMode } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gatherloop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        backgroundColor="#171717"
        height="100%"
        justify="center"
        alignItems="center"
        flexDir="column"
      >
        <Flex
          flexDir="column"
          justify="center"
          alignItems="center"
          marginBottom="30px"
        >
          <Image
            src="/gatherloop-logo.svg"
            alt="Gatherloop Logo"
            width={[250, 300, 500]}
            height={[50, 100]}
          />
          <Text
            textAlign="center"
            marginTop="15px"
            fontSize={[16, 24]}
            width={[250, 300, 500]}
            color="white"
          >
            Community Gathering Space at Kraksaan, Probolinggo, East Java
          </Text>
        </Flex>

        <Link
          _hover={{ textDecoration: "none" }}
          display="flex"
          alignItems="center"
          href="https://www.instagram.com/gatherloop/"
          border="solid 1px white"
          py="5px"
          px="15px"
          borderRadius="15px"
        >
          <Image
            src="/instagram.svg"
            alt="instagram logo"
            width={["16px", "24px"]}
            height={["16px", "24px"]}
          />
          <Text marginLeft={["5px", "10px"]} fontSize={[16, 24]} color="white">
            Instagram
          </Text>
        </Link>
      </Flex>
    </>
  );
}
